### ISSUE TITLE
Security protocols mismatch in BrowserCore.cs

### ISSUE THREAD

**Issue by Mr-160R** [Jayx239/BrowseSharp#62]
There's a security protocols configuration in the BrowserCore.cs
https://github.com/Jayx239/BrowseSharp/blob/a37094226fbc190d240efa8cc7a11cc37cd32189/BrowseSharp/Browsers/Core/BrowserCore.cs#L38

But according to the .net standard sources the SSL 3 is not allowed, please see:
https://github.com/dotnet/corefx/blob/d6173e069a9bcedfdfd7f4f41e67d23f67157b61/src/System.Net.ServicePoint/src/System/Net/ServicePointManager.cs#L39

In this case if you run a BrowseSharp browser in a .net core app you'll get a NotSupportedException exception.

**Comment by ForeverZer0** [comment]
Indeed, after some research trying to debug why I kept getting the above exception, even after manually setting `ServicePointManager.SecurityProtocol`, I discovered the hard-coded line mentioned here was just overriding it, making this unusable in .netcore app.

**Comment by Jayx239** [comment]
Thanks for pointing this out. I will remove this from the constructor. I haven't tested browsesharp with .net core, so please let me know if you find any more issues like this.

Also, did you clone the repo or are you using the nuget package?

**Comment by ForeverZer0** [comment]
I personally was using the nuget package, and was just viewing the code on github without cloning. Was hoping I could use a quick fix my making derived class of the standard browser and calling different non-public constructor, but it was not direct decedent to accomplish easily.

Thanks for the quick reply, this library looks extremely promising, exactly what I was looking for.

**Comment by Jayx239** [comment]
I am packaging and deploying the updated nuget package now with that line removed. Version 0.0.8 will be available within the next hour.

**Comment by ForeverZer0** [comment]
Fantastic, thank you so much. :)
