### ISSUE TITLE
Possible To Add a Renderer For Basic Webpage?

### ISSUE THREAD

**Issue by protegesolutions** [Jayx239/BrowseSharp#87]
Hi, please excuse my naivety; I'm not really a web guy.

I need to replace the old _WebBrowser_ control with a browser that supports JS and CCS3 and that looks like a modern browser (such as Mozilla or Chrome) in a .NET class library that is consumed by third-party apps. All we need a browser for is to facilitate _oAuth2_ (re-)authorization by a user as required.

I've looked at a lot of options and came close to using _WebView2_ but it is unbelievable unwieldy to distribute in a single file dll.

I realize your _BrowseSharp_ is headless, but can it be augmented with a renderer? Or should I simply populate a basic win form with the few fields I need and submit the completed form? I'm obviously a bit lost here, tho I do have a lot of years or .NET dev experience.

I'm happy to take this discussion offline if that would suit you better.

Thanks.

**Comment by Jayx239** [comment]
Hi,
Thanks for reaching out, I have a few questions about your use case so I can get a better understanding of how I can help.

1. Is this embedded into a winforms app?
2. Is your ui html based? Are you trying to render an html input form in the web view?
3. What is the flow of your use case. What is the entry point? Are you just taking user input, making a request to an auth server and getting back the token?

As far as augmenting it to have a renderer, that is not the intended purpose of this project. This project is meant to be used to programmatically interact with web sites and API's as opposed to providing a presentation layer to end users.

That being said, as you mentioned you could create a winform as your presentation layer, collect the required form data, and pass it to your controller layer to make the request to your Auth servers via browse sharp. For this solution you wouldn't need webview or web browsers, but I'm not sure if this fits your use case.

**Comment by protegesolutions** [comment]
Hi @Jayx239 and thanks for your reply.

In the end we found another, less-elegant-but-robust way to do this. Essentially, I pop up the oAuth2 URI to the user, if (re-)authorization is required, which they can click on or copy/paste to complete auth in a browser of their choice, then copy back the callback URI to the app for token sync. No, it's not pretty, but this is a very occasional procedure in the class library/app - initial auth and when/if the tokens get stale or corrupted.

Cheers and thanks for getting back to me.

**Comment by Jayx239** [comment]
That sounds fine for a class library, basically your delegating responsibility to the package users to do the verification process, but giving them enough info to do so.

If this was a webapp though, you could basically create a proxy to the oAuth2 services and have the user fill in a form and you manage the authenticating and retrieving the token all in the backend. Browsesharp would support this if they are using standard forms. If they are using a lot of js, you would probably have to figure out their API's and you could make direct calls which browseharp also supports.

But anyways, glad you found a solution. Thanks for reaching out, and good luck with your project!
